### ISSUE TITLE
Bibtex Author connector should be "and"

### ISSUE THREAD

**Issue by mnoukhov** [mila-iqia/paperoni#2]
Author names in bibtex need to be connected with "and" (www.texfaq.org/FAQ-manyauthor)

Currently the bibtex author names are connected with "," with "and" only at the end (see [paperoni/papers.py line 43](https://github.com/mila-iqia/paperoni/blob/b47349b05a2918e1132326d29bd0e823f464ec3e/paperoni/papers.py#L403)) This causes an error in latex compilation (e.g. Overleaf)

e.g. 
```
@inproceedings{zhang2019-convolutional15,
    author = {Linfeng Zhang, Jiebo Song, Anni Gao, Jingwei Chen, Chenglong Bao and Kaisheng Ma},
    title = {Be Your Own Teacher: Improve the Performance of Convolutional Neural Networks via Self Distillation},
    year = {2019},
    booktitle = {2019 IEEE/CVF International Conference on Computer Vision (ICCV)},
    pages = {3712-3721},
    publisher = {IEEE}
}
```

Whereas the author list should be 

`author = {Linfeng Zhang and Jiebo Song and Anni Gao and Jingwei Chen and Chenglong Bao and Kaisheng Ma}`

**Comment by breuleux** [comment]
You're right, thanks for reporting this!

I fixed the issue and published v0.1.6.
