### ISSUE TITLE
Session restart?

### ISSUE THREAD

**Issue by d3sm0** [mila-iqia/paperoni#3]
Hi,
Thanks for the tool  looks neat. Is there an easy way to keep the cli alive, and search for other papers? or is something that might break the API?

**Comment by breuleux** [comment]
You mean falling back to a prompt after a search so that you can just type new search terms? That would be possible, certainly. I'm not sure what the interface for the prompt should be, though. What interface were you thinking?

**Comment by d3sm0** [comment]
I'm now using a general search for words. The use case I have in mind is when writing  up one need a quick access of a known paper. Usually I google, find the paper, copy the ref and paste it in tex file.
With your tool i can search with `paperoni search --word $1`, copy the bibtex in the clipboard (i can open a PR for this if useful to anyone) and move to the next item. So much faster.

I guess this search --word is the most general, for everything else  you can start a more specific session.

**Comment by breuleux** [comment]
You can use `paperoni bibtex --word $1 >> refs.bib` instead of copy/paste, if that fits your workflow. I do like the idea of copying into the clipboard, though, this is likely more useful than printing it out. I'd welcome a PR for that :)

**Comment by d3sm0** [comment]
With that approach i'm betting on the fact that the first thing it finds is the right one. But i'll deal with that with the alias :+1:
